#cloud-config
users:
  - name: vmuser
    primary_group: vmusergroup
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo, wheel
    ssh_import_id: None
    lock_passwd: true
    ssh_authorized_keys:
      - $your_public_key
runcmd:
  - echo 'foo' >> /tmp/bar.txt
  - [ bash, /usr/bin/post-install-script]
  - touch '/etc/cloud/cloud-init.disabled'